package com.example.emptyactivity.data.remote.supabase.dto

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Data Transfer Object (DTO) for menu data from Supabase.
 *
 * This DTO represents the structure of menu data as stored in the Supabase `user_menu` table.
 * It uses @SerialName annotations to map between Kotlin property names and the database column
 * names (which use snake_case).
 *
 * This DTO is used for deserializing menu data from Supabase responses and is converted to
 * the domain Menu model by the MenuRepositoryImpl.
 *
 * @param menuId The unique identifier of the menu (primary key in database).
 * @param userId The unique identifier of the user who saved this menu (foreign key).
 * @param menuText The original OCR-extracted menu text.
 * @param menuItemsJson JSON string containing serialized menu items. Can be null if
 *                      menu items haven't been analyzed yet.
 * @param imageUri Optional URI string of the original menu image. Can be null if no
 *                 image was provided.
 * @param createdAt Timestamp when the menu was created, as a string from the database.
 *                  Can be null for older records.
 *
 * Mostly created by: Muhammad
 */
@Serializable
data class MenuDto(
    @SerialName("menu_id")
    val menuId: String,
    @SerialName("user_id")
    val userId: String,
    @SerialName("menu_text")
    val menuText: String,
    @SerialName("menu_items_json")
    val menuItemsJson: String? = null,
    @SerialName("image_uri")
    val imageUri: String? = null,
    @SerialName("created_at")
    val createdAt: String? = null,
)

/**
 * Data Transfer Object (DTO) for creating a new menu in Supabase.
 *
 * This DTO represents the structure required to insert a new menu into the Supabase
 * `user_menu` table. It's used when saving a menu and doesn't include fields that are
 * auto-generated by the database (like menuId and createdAt).
 *
 * @param userId The unique identifier of the user saving the menu.
 * @param menuText The original OCR-extracted menu text.
 * @param menuItemsJson JSON string containing serialized menu items. Can be null.
 * @param imageUri Optional URI string of the original menu image. Can be null.
 */
@Serializable
data class CreateMenuDto(
    @SerialName("user_id")
    val userId: String,
    @SerialName("menu_text")
    val menuText: String,
    @SerialName("menu_items_json")
    val menuItemsJson: String? = null,
    @SerialName("image_uri")
    val imageUri: String? = null,
)
